version: '3'

services:

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

    ports:
      - "3307:3306"
    
    networks:
      - my_network   

    restart: always

    
  backend:
    container_name: backend
    build: .
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn mirasonabi.wsgi --bind 0.0.0.0:8000"
    volumes:
      - .:/backend
      - static_volume:/backend/static_file
      - media_volume:/backend/media
    expose:
      - "8000"
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_PORT=3306
      - debug=True
      - ALLOWED_HOSTS = localhost ,
    networks:
      - my_network
    restart: always

    depends_on:
      - db


  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx_dev.conf:/etc/nginx/nginx.conf
      - static_volume:/home/backend/static
      - media_volume:/home/backend/media

    networks:
      - my_network  

    depends_on:
      - backend
      
    restart:
      always

    

volumes:
  static_volume:
  media_volume:
  mysql_data:  # اضافه شده برای MySQL

networks:
  my_network:
    driver: bridge