version: '3'

services:

  backend:
    container_name: backend
    # مسیری که باید دنبال داکر فایل بگرده 
    build: .
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/backend
      - static_volume:/backend/static_file
      - media_volume:/backend/media
    expose:
      - "8000"
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_PORT=3306
      - debug=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DJANGO_ENV=development

    networks:
      - shared_net
    restart: always


volumes:
  static_volume:
  media_volume:

networks:
  shared_net:
    external: true