version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - my_network
    restart: always

  backend:
    container_name: backend
    build: .
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn mirasonabi.wsgi --bind 0.0.0.0:8000"
    volumes:
      - .:/backend
      - static_volume:/backend/static_file
      - media_volume:/backend/media
    expose:
      - "8000"
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_PORT=3306
    networks:
      - my_network
    restart: always
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot_www:/var/www/certbot
      - ./certs:/etc/letsencrypt
      - static_volume:/home/backend/static
      - media_volume:/home/backend/media
    networks:
      - my_network
    depends_on:
      - certbot
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot_www:/var/www/certbot
    entrypoint: sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot -d kanoonmns.ir -d www.kanoonmns.ir --email solaimoon00@gmail.com --agree-tos --no-eff-email && trap exit TERM; while :; do sleep 12h & wait $${!}; done"
    networks:
      - my_network
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
  mysql_data:
  certbot_www:

networks:
  my_network:
    driver: bridge
