# Generated by Django 4.2 on 2025-11-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='تیتر')),
                ('file', models.FileField(upload_to='media/', verbose_name='فایل ')),
                ('slug', models.CharField(max_length=50)),
                ('image', models.ImageField(default='null', upload_to='media_night', verbose_name='تصویر نمایه')),
                ('discription', models.CharField(max_length=2000)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
            ],
            options={
                'verbose_name': ' کلیپ',
                'verbose_name_plural': ' کلیپ ها',
            },
        ),
    ]
