# Generated by Django 4.2 on 2025-02-24 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='type_emtiyaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ramazan_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('create_at', django_jalali.db.models.jDateTimeField()),
                ('Time_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramazan.time_period')),
                ('own_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_user', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ramazan.type_emtiyaz')),
                ('user_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_register', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
