# Generated by Django 4.2 on 2025-03-05 19:53

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ramazan', '0002_time_period_date_hejri_time_period_date_shamsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramazan_point',
            name='create_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
