# Generated by Django 4.2 on 2025-11-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramazan', '0003_alter_ramazan_point_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ramazan_final',
            fields=[
                ('rotbe', models.IntegerField(primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField()),
                ('period', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ramazan_final',
                'managed': False,
            },
        ),
    ]
