# Generated by Django 4.2 on 2024-10-18 11:28

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sum_emtiyazat',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date_for', django_jalali.db.models.jDateField()),
                ('sumed_emtiyaz', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'sum_emtiyazat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SUM_final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUM', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'SUM_final',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avalable', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_for', django_jalali.db.models.jDateField()),
                ('creat_at', models.DateField(auto_now_add=True, null=True)),
                ('method', models.CharField(choices=[('kosha_ravankhani', 'kosha_ravankhani'), ('kosha_tajvid', 'kosha_tajvid'), ('noramal', 'noramal')], max_length=50)),
                ('ons', models.PositiveIntegerField(null=True)),
                ('enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.link_table')),
            ],
        ),
        migrations.CreateModel(
            name='presence_absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_or_not_or', models.CharField(choices=[('present', 'حاضر'), ('absent_unwarranted', 'غایب/غیر موجه'), ('absent_warranted', 'غایب/موجه')], max_length=50)),
                ('time', models.TimeField(null=True)),
                ('date', django_jalali.db.models.jDateField()),
                ('enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.link_table')),
            ],
        ),
        migrations.CreateModel(
            name='amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.score')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='score.type')),
            ],
        ),
    ]
