# Generated by Django 4.2 on 2025-02-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sum_emtiyazat',
            table='sum_emtiyazat_for_each_day',
        ),
    ]
