# Generated by Django 4.2 on 2025-02-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compattions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=500)),
                ('monasebat', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('image', models.ImageField(default='NULL', null=True, upload_to='compatitons/')),
                ('audio_or_video', models.FileField(default='NULL', null=True, upload_to='compatitons/')),
            ],
        ),
    ]
