# Generated by Django 4.2 on 2025-02-26 21:07

from django.db import migrations
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('compattions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compattions',
            name='creat_at',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now),
        ),
    ]
