# Generated by Django 4.2 on 2024-10-18 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='شماره تلفن ')),
                ('owner', models.CharField(blank=True, choices=[('itself', 'شخصی'), ('father', 'پدر'), ('mather', 'مادر')], max_length=6, verbose_name='مالکیت')),
                ('forign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='extra_user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='سن')),
                ('adress', models.CharField(blank=True, max_length=500, null=True, verbose_name='ادرس')),
                ('type', models.CharField(blank=True, choices=[('operator', 'اوپراتور'), ('teacher', 'معلم'), ('student', 'دانش اموز'), ('Guest', 'مهمان')], default='Guest', max_length=50, null=True)),
                ('meli_cood', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد ملی')),
                ('sex', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=50, null=True)),
                ('image', models.ImageField(default='personality_picture/boy.png', upload_to='personality_picture/')),
                ('forign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
