# Generated by Django 4.2 on 2024-10-18 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('course', models.PositiveIntegerField()),
                ('start_date', django_jalali.db.models.jDateField()),
                ('end_data', django_jalali.db.models.jDateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='level_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='link_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_of_class', models.CharField(choices=[('studing', 'در حال تحصیل'), ('pass', 'قبول'), ('fail', 'مردود')], default='studing', max_length=30)),
                ('klass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.klass')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='klass',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.level_class'),
        ),
        migrations.AddField(
            model_name='klass',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='have_staudent', through='enroll.link_table', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='klass',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='have_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
